config/routes.rb
Rails.application.routes.draw do
	namespace :https, id: /[^\/]+/ do
		get ':id/', action: :show
		get ':id/refresh', action: :refresh, as: :refresh
	end

	namespace :smtp, id: /[^\/]+/ do
		get ':id/', action: :show
		get ':id/refresh', action: :refresh, as: :refresh
	end

	namespace :xmpp, id: /[^\/]+/ do
		get ':id/', action: :show
		get ':id/refresh', action: :refresh, as: :refresh
	end

	namespace :tls, id: /[^\/]+/ do
		get '/', action: :index
		get ':id/', action: :show
		get ':id/refresh', action: :refresh, as: :refresh
	end

	namespace :ssh, id: /[^\/]+/ do
		get '/', action: :index
		get ':id/', action: :show
		get ':id/refresh', action: :refresh, as: :refresh
	end

	get 'ciphers' => 'site#ciphers'
	get 'suite' => 'site#suite_index'
	get 'suite/:id' => 'site#suite'
	post 'suite' => 'site#suite'
	root 'site#index'
	post '/' => 'site#check'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	include HttpAcceptLanguage::AutoLocale
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.erb
<div id="flash" class="container">
	<% [:danger, :warning, :success, :info].each do |level|
		message = flash[level]
		unless message.nil? %>
			<%= content_tag :div, class: %(alert alert-#{level}) do %>
				<% if message.is_a? Enumerable %>
					<ul>
						<% message.each do |m| %>
							<li><%= m %></li>
						<% end %>
					</ul>
				<% else %>
					<%= message %>
				<% end %>
			<% end
			   end
			   end %>
</div>

app/views/application/_headers.erb
<header>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<span>
					<%= link_to 'CryptCheck', root_path, class: %i(navbar-brand) %>
				</span>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to 'HTTPS / SMTP / XMPP', root_path %></li>
				<li><%= link_to 'TLS', tls_path %></li>
				<li><%= link_to 'SSH', ssh_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to t('User agent compatibility'), suite_path %></li>
				<li><%= link_to t('Supported ciphers'), ciphers_path %></li>
				<!--
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						Hall of f/sh·ame
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">Misc</a></li>
						<li><a href="#">Syndicats</a></li>
						<li><a href="#">SecureDrop</a></li>
						<li><a href="#">Presse</a></li>
						<li><a href="#">Top 500 Alexa</a></li>
						<li><a href="#">Porn</a></li>
						<li><a href="#">US gov</a></li>
					</ul>
				</li>
				-->
			</ul>
		</div>
	</nav>
</header>